version: '2'
services:
  django-api:
    environment:
      - HOSTNAME=${HOSTNAME}
      - HOST_URL=${HOST_URL}
      - DJANGO_ENV=${DJANGO_ENV}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - STATIC_ROOT=${STATIC_ROOT}
      - STATIC_URL=${STATIC_URL}
      - QUOTA=${QUOTA}
    network_mode: "host"
    ports:
      - "4000:4000"
    volumes:
      - /home/tiago/works/api/radar/api/static:/var/www/static
    container_name: django-radartona
    image: alien9/radartona
    build:
      context: .
#      dockerfile: dev.Dockerfile
