# Generated by Django 3.1.4 on 2020-12-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radar',
            name='data_publicacao',
            field=models.DateField(default='2011-01-01'),
            preserve_default=False,
        ),
    ]
