# Generated by Django 3.1.4 on 2020-12-11 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_radar_data_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade', models.IntegerField()),
                ('faixa', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('contagem', models.IntegerField()),
                ('autuacoes', models.IntegerField()),
                ('placas', models.IntegerField()),
                ('data_e_hora', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Contagem',
                'db_table': 'contagens',
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.IntegerField()),
                ('data_inicio', models.DateTimeField()),
                ('final', models.IntegerField()),
                ('data_final', models.DateTimeField()),
                ('tipo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Viagem',
                'db_table': 'viagens',
            },
        ),
        migrations.CreateModel(
            name='Trajeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('data_inicio', models.DateTimeField()),
                ('data_final', models.DateTimeField()),
                ('origem', models.IntegerField()),
                ('destino', models.IntegerField()),
                ('v0', models.IntegerField()),
                ('v1', models.IntegerField()),
                ('viagem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.viagem')),
            ],
            options={
                'verbose_name': 'Trajeto',
                'db_table': 'trajetos',
            },
        ),
    ]
