# Generated by Django 3.1.4 on 2020-12-17 05:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
