# Generated by Django 3.1.4 on 2020-12-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_route_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radar',
            name='bairro',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='radar',
            name='data_publi',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='radar',
            name='data_publicacao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='radar',
            name='endereco',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='radar',
            name='enquadrame',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='radar',
            name='lote',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='radar',
            name='qtde_fxs_f',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='radar',
            name='referencia',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='radar',
            name='sentido',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='radar',
            name='tipo_equip',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='radar',
            name='velocidade',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='radar',
            name='velocidade_cam_oni',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='radar',
            name='velocidade_carro_moto',
            field=models.IntegerField(null=True),
        ),
    ]
