# Generated by Django 3.1.4 on 2020-12-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201223_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='tipo',
            field=models.IntegerField(null=True),
        ),
    ]
